add_spell(spell.none, "------", "You don't have any spells", 0, 0, spell_type.single, small_fireball)
add_spell(spell.fireball, "Fireball", "A less-than-great ball of fire. The energy stored in this orb of flame will release when it finds its target, damaging anything within range of its detonation.", 16, 2, spell_type.aoe, small_fireball)
add_spell(spell.ice_ball, "Iceball", "A ball of ice, disguised as a snowball thanks to a thin layer of snow. This will only hit one target, but it'll hurt them something decent.", 30, 4, spell_type.single, iceball)
add_spell(spell.mend, "Mend", "Apply a weak spell to heal a small amount of damage. You'll still feel hungry, though.", 15, 5, spell_type.auto_cast, mend_effect)
add_spell(spell.infernal_armor, "Infernal Armor", "Draw on the essence of slain demons to craft a temporary set of armor, halving all damage taken for an hour.", 0, 0, spell_type.auto_cast, mend_effect, 50)
add_spell(spell.essence_edge, "Essence Edge", "Expel the essence stored within your weapon, super-charging it and doubling all damage done for an hour.", 0, 0, spell_type.auto_cast, mend_effect, 25)
add_spell(spell.quake, "Quake", "Cause a mighty earthquake, slightly damaging all enemies on the current floor.", 5, 8, spell_type.auto_cast, quake_spell)
add_spell(spell.town_port, "Town Teleport", "Teleports you back to Sargoza. Requires 30 minutes to charge, although you can move during those 30 minutes.", 0, 0, spell_type.auto_cast, mend_effect)
add_spell(spell.hellfire, "Hellfire", "Emit a blast of searing, hellish heat, with you as the epicenter.", 40, 0, spell_type.auto_cast, explosion, 75)
add_spell(spell.concentrate, "Concentrate", "Clear your mind and focus on your inner demon, trading energy for essence.", 0, 5, spell_type.auto_cast, mend_effect)
add_spell(spell.sense_mind, "Sense Mind", "Allows you to sense where all enemies on the floor are.", 0, 20, spell_type.auto_cast, mend_effect)
add_spell(spell.demon_form, "Demon Form", "Unleash your inner demon for 60 minutes. Your damage given will be doubled, your damage received halved, and you will slowly regenerate health the entire time.", 0, 0, spell_type.auto_cast, mend_effect, 100)
add_spell(spell.slow, "Slow", "Cast a hex on your target, halving how fast they move for 30 minutes. Further casts will increase their time slowed donw by 15 minutes.", 0, 10, spell_type.single, slow_effect)
add_spell(spell.stealth, "Stealth", "Shroud yourself in darkness, allowing you to move without being attacked for 30 minutes. Great for some one-sided fighting...or fleeing.", 0, 15, spell_type.auto_cast, mend_effect)
add_spell(spell.aoe_explosion, "Explosion", "Concentrate your arcane energy to release a devastating explosion around you.", 14, 7, spell_type.auto_cast, mend_effect)
add_spell(spell.landmine, "Landmine", "Lay an arcane landmine. Will explode when an enemy step on it.", 18, 8, spell_type.single, placed_landmine) 
add_spell(spell.magic_pillar, "Magic Pillar", "Erect a magic pillar that will deal magic damage to nearby enemies.#The pillar's damage scales with your weapon's Magic, and the pillar's longeivity scales with your Wisdom.", 11, 9, spell_type.single, magic_pillar_obj) 
