add_buff(buff.none, "None", "Nothing.", s_useless)
add_buff(buff.health_gain, "Healing", "Healing one HP a minute.", s_health_gain)
add_buff(buff.energy_gain, "Digesting", "Gaining one energy a minute.", s_energy_gain)
add_buff(buff.infernal_armor, "Infernal Armor", "All damage received is halved.", s_infernal_armor)
add_buff(buff.essence_edge, "Essence Edge", "All damage given is doubled.", s_essence_edge)
add_buff(buff.teleporting, "Teleporting", "Preparing to get back to Sargoza.", s_teleporting)
add_buff(buff.invincibility, "Invincibility", "You're completely invincible.", s_invincibility)
add_buff(buff.demon_form, "Demon Form", "Double damage, double defense, health regen.", s_demon_form_buff)
add_buff(buff.rested, "Rested", "You got some good sleep. 1.5x XP gain, slight HP regen.", s_rested_buff)
add_buff(buff.stealth, "Stealth", "You are invisible. A wind, yet to be broken.", s_stealth_buff)
add_buff(buff.gold_on_hit, "Golden Touch", "You are gaining gold on every hit you land.", s_gold_on_hit)
add_buff(buff.double_resist, "Fortified", "Your resistances are doubled in combat.", s_double_resist)
add_buff(buff.enchanted_wep, "Enchanted Weapon", "You are dealing additional magic damage.", s_enchanted_wep)
add_buff(buff.poisoned, "Poisoned", "Lose 1% of your max HP every minute.", s_poisoned)
add_buff(buff.second_chance_debuff, "Second Chance", "You survived a brush with death and need to heal.", s_second_chance)
add_buff(buff.guardian_angel_debuff, "Angel's Rest", "Your Guardian Angel needs rest.", s_guardian_angel)
add_buff(buff.enraged, "Enraged", "Extra dmg taken and received. More foul language.", s_enraged)
add_buff(buff.sated, "Sated", "Consuming blood won't heal right now.", s_sated_icon)
