//this will now work for any "none" slots
add_weapon(item.none, "------", "Nothing", 0, 0, 0, 0, 1, weapon_type.melee , false, 0, s_shortsword, "none", 2)


//Weapons
add_weapon(item.short_sword, "Dagger", "A standard tool of death. Popular with vagrants and guards alike.", 3, 0, 0, 0, 1, weapon_type.melee , false, 15, s_shortsword, "short_sword", 1)
add_weapon(item.long_sword, "Iron Blade", "A heavy, but effective blade. Standard-issue for Regent Knight recruits.", 6, 0, 0, 0, 2, weapon_type.melee , false, 48, s_longsword, "long_sword", 1)
add_weapon(item.old_spear, "Old Spear", "A fallen soldier's spear. Judging by the dents, nicks, and wear and tear on it, it was at least well-loved.", 0, 0, 6, 0, 2, weapon_type.melee , false, 23, s_spear, "old_spear", 1)
add_weapon(item.two_by_four, "2x4", "This board of legend is said to have been used to defeat the Grand Infernal, Korum'Zal. Or it's just a piece of wood.", 0, 7, 0, 0, 1, weapon_type.melee, false, 19, s_club, "two_by_four", 1)
add_weapon(item.hatchet, "Hatchet", "An axe with a blunt backend. Hailed by survivalists as a must-have tool, should one be stranded.", 4, 0, 3, 0, 1, weapon_type.melee, false, 17, s_1h_axe, "hatchet", 1)
add_weapon(item.woodaxe, "Wood-Axe", "An axe allegedly made for chopping down trees. Some have found more...creative uses for these with the advent of the fiend invasion.", 5, 1, 4, 0, 2, weapon_type.melee, false, 78, s_2h_axe, "woodaxe", 1)
add_weapon(item.halberd, "Halberd", "A polearm once used by a Regent Knight. Said Knight must have liked their weapon quite a bit, as they named their ship the Halberd as well.", 7, 0, 5, 0, 2, weapon_type.melee, false, 85, s_2h_axe, "halberd", 2)
add_weapon(item.shiv, "Shiv", "A crudely-constructed shiv, made from some dull-colored rock. The blade is stained dark red, so at least its former owner got some use out of it.", 0, 0, 5, 0, 1, weapon_type.melee, false, 15, s_shortsword, "shiv", 1)
add_weapon(item.rusty_saber, "Rusty Saber", "An old, corroded saber. It still has a slightly sharp edge, although it's more likely to kill its target via tetanus than bleeding.", 4, 0, 0, 0, 1, weapon_type.melee, false, 25, s_shortsword, "rusty_saber", 1)
add_weapon(item.infantry_blade, "Infantry Blade", "A common sword, used by soldier and mercenary alike. This sword is the idea of 'boring, but practical' made tangible.", 8, 0, 0, 0, 1, weapon_type.melee, false, 100, s_shortsword, "infantry_blade", 2)
add_weapon(item.dirk, "Dirk", "A short dagger. Its lethality lies somewhere between a wet noddle and a rigid noodle.", 6, 0, 0, 0, 1, weapon_type.melee, false, 70, s_shortsword, "dirk", 2)
add_weapon(item.fighting_gloves, "Fighting Gloves", "A pair of heavy gloves, reinforced to do more than bruise their target. Please refrain from repeatedly hitting the enemy and yelling while using these.", 0, 13, 0, 0, 2, weapon_type.melee, false, 150, s_gauntlet, "fighting_gloves", 2) 
add_weapon(item.brass_knuckle, "Brass Knuckle", "A heavy gauntlet, adorned with menacing spikes.", 0, 8, 7, 0, 1, weapon_type.melee, false, 110, s_gauntlet, "brass_knuckle", 2)
add_weapon(item.bowie_knife, "Bowie Knife", "A large, but compact, blade, with an attached knuckle-duster. When asked if this was a sword or knife, its creator answered 'Yes'.", 8, 0, 2, 0, 1, weapon_type.melee, false, 300, s_shortsword, "bowie_knife", 2, enemy_race.undead)
add_weapon(item.blackjack, "Blackjack", "A small, solid stick made of metal. Perfect for bopping people in the back of the head with.", 0, 11, 0, 0, 1, weapon_type.melee, false, 100, s_club, "blackjack", 2)
add_weapon(item.winged_spear, "Winged Spear", "An ornate spear made of steel. The tip is long, and guaranteed to pierce through most foes.", 0, 0, 20, 0, 2, weapon_type.melee, false, 150, s_spear, "winged_spear", 2)
add_weapon(item.rapier, "Rapier", "A thin sword made for stabbing, not slashing. An elegant weapon, it is still very deadly in the right hands. Maybe it's time to use your rapier wit to snark the fiends into submission.", 0, 0, 8, 0, 1, weapon_type.melee, false, 410, s_longsword, "rapier", 3)
add_weapon(item.zweihander, "Zweihander", "A mighty two-handed blade that will, if not cut, crush anything in its way. It is adorned with a lightning bolt motif, for some reason.", 14, 4, 0, 3, 2, weapon_type.melee, true, 190, s_longsword, "zweihander", 2)
add_weapon(item.treetrunk, "Tree Trunk", "...really?", 0, 14, 0, 0, 2, weapon_type.melee, false, 93, s_club, "tree_trunk", 2)
add_weapon(item.executionaxe, "Executioner's Axe", "A mighty axe, used to seperate heads from bodies in a (hopefully) clean manner. The blade is clean, so either it hasn't been used, or its previous owenr was very meticulous about cleaning it.", 9, 0, 4, 0, 2, weapon_type.melee, false, 119, s_2h_axe, "executioners_axe", 2)
add_weapon(item.leatherwhip, "Leather Whip", "A whip with a metal tip. Being the first object to break the speed of sound, the whip has had a venerable history in warfare. It's also prized among fiend hunters and delvers alike. This one has been enchanted, and will both deal magic damage and act as a catalyst, and was made for (re-)killing the undead.", 6, 0, 0, 2, 1, weapon_type.melee, true, 150, s_whip, "leather_whip", 2, enemy_race.undead)
add_weapon(item.mallet, "Mallet", "A mallet made from hardened rubber. Surprisingly heavy for its size. A wise sage once said 'When all else fails, use a rubber mallet'.", 0, 11, 0, 0, 1, weapon_type.melee, false, 98, s_hammer, "mallet", 1)
add_weapon(item.warhammer, "Warhammer", "A giant hammer made for war, naturally. While some disparage it for its brutality and basic nature, there are those who respect the path of the Hammermaster. Especially when the Hammermaster is the dealer of justice in a given community.", 0, 22, 0, 0, 2, weapon_type.melee, false, 217, s_hammer, "warhammer", 2)
add_weapon(item.devblade, "Devblade", "You really shouldn't have this. If you do, then...don't. -Nick", 999, 999, 999, 999, 1, weapon_type.melee, true, 9999, s_devblade, "devblade", 99)
add_weapon(item.wrath, "Wrath", "A blade forged from pure Yzorium and imbued with the souls of many. It's said that these souls drive its wielder mad.", 120, 0, 23, 65, 2, weapon_type.melee, true, 8500, s_longsword, "wrath", 8)
add_weapon(item.bent_staff, "Bent Staff", "A crooked, gnarled staff made of oak. It has some arcane energy left in it, so it can serve as a catalyst, but it will not do anything spectacular.", 0, 4, 0, 8, 2, weapon_type.staff, false, 16, s_staff, "bent_staff", 1)
add_weapon(item.wise_staff, "Wise Staff", "Once owned by an apprentice arcanist, this staff has some elementary runes engraved in it. The wood appears alien, though...", 0, 4, 0, 13, 2, weapon_type.staff, false, 39, s_staff, "wise_staff", 2)
add_weapon(item.crooked_wand, "Crooked Wand", "A crooked, cheap wand. It appears to be made from some driftwood, with runes carved hastily into it.", 0, 1, 1, 3, 1, weapon_type.staff, false, 9, s_wand, "crooked_wand", 1)
add_weapon(item.slayer_sword, "Slayer's Sword", "A blade imbued with demonic essence. This blade was forged by a repentant demon blacksmith, who took advantage of the fact that demons require their essence to stay in their chosen form. The demon's skull on the hilt allows the blade to absorb any demonic essence it comes in contact with, greatly increasing the damage done to, and essence gained from, demons.", 5, 0, 0, 2, 1, weapon_type.melee, true, 1, s_longsword, "slayer_sword", 2, enemy_race.demon)
add_weapon(item.slayer_sword_lv2, "Slayer's Sword +1", "An upgraded copy of the Slayer's Sword. This version has had its edges sharpened, increasing its cutting ability.", 25, 0, 0, 4, 1, weapon_type.melee, true, 1, s_longsword, "slayer_sword_lv2", 3, enemy_race.demon)
add_weapon(item.slayer_sword_lv3, "Slayer's Sword +2", "A copy of the Slayer's Sword that has been further upgraded. This version has been further enchanted, meaning it will deal magic damage when performing a melee attack.", 30, 0, 0, 15, 1, weapon_type.melee, true, 1, s_longsword, "slayer_sword_lv3", 4, enemy_race.demon)
add_weapon(item.slayer_sword_lv4, "Slayer's Sword +3", "An upgraded copy of the Slayer's Sword. This version's edge has been inlaid with yzorium, massively increasing its cutting capability.", 45, 0, 0, 20, 1, weapon_type.melee, true, 1, s_longsword, "slayer_sword_lv4", 5, enemy_race.demon)
add_weapon(item.slayer_sword_lv5, "Slayer's Sword +4", "The ultimate in demon slaying. This version of the blade has been reforged with demonite, increasing its density.", 60, 15, 0, 25, 1, weapon_type.melee, true, 1, s_longsword, "slayer_sword_lv5", 8, enemy_race.demon)
add_weapon(item.brokenblade, "Broken Blade", "An old, brittle longsword that has been cleaved in half. While it still has a sharp edge, and it has some weight to it, it is a rust-covered, decrepit shell of its former self.", 2, 1, 0, 0, 1, weapon_type.melee, false, 1, s_shortsword, "broken_blade", 1)
add_weapon(item.voracious_axe, "Voracious Axe", "An axe whsoe edge is adorned with sharp teeth pulled from various fiends. Imbued with a never-ending hunger, this axe will rip through foes with ease, but at the cost of its wielder's energy.", 35, 10, 0, 0, 1, weapon_type.melee, false, 450, s_1h_axe, "voracious_axe", 3)
add_weapon(item.regent_spear, "Regent Spear", "A spear forged from steel by the Regent Knights. As knights rise thorugh the ranks, they may choose what equipment they use when called to action. Spears are often chosen for their piercing power, and the fact that they can be thrown in a pinch.", 0, 0, 27, 0, 2, weapon_type.melee, false, 480, s_spear, "regent_spear", 3)
add_weapon(item.sawblade, "Sawblade", "A straight lumberjack's saw that has been cut down to be usable by one person. It has been enchanted to be anathemic to the undead. Some would argue that the effort needed to saw through a foe makes this grisly weapon all the more cathartic to use.", 26, 0, 7, 0, 2, weapon_type.melee, false, 450, s_longsword, "sawblade", 3, enemy_race.beast)
add_weapon(item.staff_sight, "Staff of Sight", "A special staff whose top glows with a coomforting light. This weapon will let you see one tile further than usual when equipped.", 0, 6, 0, 19, 2, weapon_type.staff, false, 140, s_staff, "staff_sight", 3) 
add_weapon(item.regent_blade, "Regent Blade", "A simple, but powerful broadsword used by the Regent Knights. While seen as a simple weapon, there is no doubt that it has helped keep countless people alive throught the years.", 20, 0, 0, 0, 1, weapon_type.melee, false, 520, s_shortsword, "regent_blade", 3)
add_weapon(item.delver_maul, "Delver Maul", "Delvers often encounter dangerous, wild beasts while on their expeditions. This heavy maul serves as an excellent solution to that problem.", 4, 21, 2, 0, 1, weapon_type.melee, false, 570, s_club, "delver_maul", 3, enemy_race.undead)
add_weapon(item.arcane_staff, "Arcane Staff", "One of the Arcane Alliance's most prolific pieces of equipment. Even for something that is mass-produced, the runic carvings on this staff are exquisite, and its arcane presence is easily noticeable.", 0, 0, 0, 29, 2, weapon_type.staff, false, 560, s_staff, "arcane_staff", 3)
add_weapon(item.chain_whip, "Chain Whip", "A whip made of serrated chains. This weapon will make short work of any undead you tangle with. The tip of the whip is adorned by an orb that menaces with spikes of silver. This weapon is enchanted, meaning it will both deal magic damage and can be used as a catalyst.", 18, 0, 0, 7, 1, weapon_type.melee, true, 590, s_whip, "chain_whip", 3, enemy_race.undead)
add_weapon(item.obelisk, "Obelisk", "This is literally just a slade obelisk that you're using to bludgeon your foes to death. One has to question the mental state of whoever has been using two-handed blunt weapons throughout the Tower.", 0, 43, 0, 0, 2, weapon_type.melee, false, 680, s_hammer, "obelisk", 4)
add_weapon(item.uber_greatsword, "Uber Greatsword", "There once was a strong, muscle-bound smith who live don a mountain. He forged all kinds of exquisite, intricate weapons, using the unique ore of the mountain in his work. One day, he found himself facing a creativity block. Thus, he hauled some stone from the top of the mountain and carved this behemoth of a 'blade'.", 10, 30, 0, 0, 2, weapon_type.melee, false, 730, s_longsword, "uber_greatsword", 4)
add_weapon(item.steel_saber, "Steel Saber", "An elegant saber, crafted for maximized efficiency in the dispensation of death. Sometimes, all you need is a well-made, simple sword to get the job done.", 36, 0, 0, 0, 1, weapon_type.melee, false, 680, s_shortsword, "steel_saber", 4)
add_weapon(item.puncture, "Puncture", "A special dagger made for piercing. This design was commissioned by an assassin in anceint times, and has been loved throughout history for its concealability, and the fact that it leaves very small, but deep, wounds.", 0, 0, 36, 0, 1, weapon_type.melee, false, 650, s_shortsword, "puncture", 4)
add_weapon(item.flail, "Flail", "A heavy steel ball on the end of a chain on the end of a stick. Few things in monster-slaying life are more satsfying than whipping this tool around and watching it collide with the target's head.", 0, 35, 0, 0, 1, weapon_type.melee, false, 680, s_whip, "flail", 4)
add_weapon(item.hinteroak_wand, "Hinteroak Wand", "The Hinterlands are unique in the potency of their arcane presence. This would be a great boon to the Arcane Alliance...were it not for the fact that the Hinterlands are also unique for the sheer number of powerful fiedns that live there.", 0, 6, 0, 34, 1, weapon_type.staff, false, 640, s_wand, "hinter_wand", 4)
add_weapon(item.hinteroak_staff, "Hinteroak Staff", "The Arcane Alliance was thrilled to learn that more powerful equipment could be made from Hinterlands materials, thanks to the area's high concentration of arcane energy. They were less thrilled to learn that these materials were guarded by multiple hellish hordes of fiends.", 0, 15, 0, 41, 2, weapon_type.staff, false, 730, s_staff, "hinter_staff", 4)
add_weapon(item.gungnir, "Gungnir", "A once-legendary staff that has lost some of its powers over the eons. Even with said loss of power, this grand lance is still something to be feared.", 0, 0, 40, 0, 2, weapon_type.melee, false, 710, s_spear, "gungnir", 4)
add_weapon(item.bastard_sword, "Bastard Sword", "The sword with a naughty word in its name. Nobody is really sure why they're called that, although it's probably not becuase this sword doesn't know its father. Swords can't have families, that'd just be silly.", 42, 0, 0, 0, 2, weapon_type.melee, false, 700, s_longsword, "bastard_sword", 4)
add_weapon(item.yew_wand, "Yew Wand", "A powerful wand hewn from an enchanted yew tree. Some areas of the world are inexplicably infused with a high amount of arcane energy. This energy is asborbed by the trees in the area, making them ideal for staff and wand crafting. These areas are heavily guarded by the Arcane Alliance.", 0, 0, 0, 18, 1, weapon_type.staff, false, 460, s_wand, "yew_wand", 2)
add_weapon(item.headhunter, "Headhunter", "Axe falls. Head rolls. Sun rises. Sun sets.", 23, 10, 0, 0, 2, weapon_type.melee, false, 600, s_2h_axe, "headhunter", 3, enemy_race.human)
add_weapon(item.basher_staff, "Basher Staff", "A unique staff that has been imbued with arcane energy. While this can be used to cast spells well enough, it can also double as an effective melee weapon.", 0, 10, 0, 11, 2, weapon_type.staff, false, 65, s_staff, "basher_staff", 2)
add_weapon(item.mystic_dagger, "Mystic Dagger", "A dagger inscribed with inscrutable runes. While the runes are illegible, the aura given off by this sharp, jagged piece of iron belies the arcane power held within.#This weapon is enchanted, and will deal magic damage if used as a melee weapon.", 6, 0, 0, 9, 1, weapon_type.melee, true, 78, s_shortsword, "mystic_dagger", 2, enemy_race.enchanted)
add_weapon(item.heavy_spellbook, "Heavy Spellbook", "A spellbook written in an ancient, unkown language. While you don't have time to translate the writings within, it turns out that a large object applied judiciously to the enemy's face is powerful in its own right.", 0, 17, 0, 14, 1, weapon_type.melee, false, 250, s_tome, "heavy_spellbook", 3)
add_weapon(item.erudite_smasher, "Erudite Smasher", "A staff that is topped with a granite sculpture of a brain. Not only does the brain confer great arcane power to the staff (somehow), but it makes an excellent bludgeon, as well.", 0, 22, 0, 50, 2, weapon_type.staff, false, 1915, s_staff, "erudite_smasher", 5)
add_weapon(item.tentacle_wand, "Yg-Zavarog's Will", "A dried-up tentacle that once belonged to one of the Great Infernals, Yg-Zavarog. Luckily, their mind-shattering aura and reality-warping powers have dissipated, leaving an exceptionally powerful, if morbid, catalyst behind.", 0, 2, 0, 39, 1, weapon_type.staff, false, 666, s_wand, "tentacle_wand", 4) 
add_weapon(item.boreal_pickaxe, "Boreal Pickaxe", "Borea is well-known for their unique, high-quality steel. Most of the steel they proudce is kept within their borders, used to make mighty weapons and tools, such as this behemoth of a pickaxe.", 0, 12, 21, 0, 2, weapon_type.melee, false, 610, s_longsword, "boreal_pick", 3)
add_weapon(item.boreal_sledge, "Boreal Sledge", "A massive, dense sledgehammer. The Boreal Territories are notoriously tree-starved, meaning that the Borean natives have had to work mostly in stone and metal. Refining and hauling these materials lend themselves to excellent strength-training, hence their heavier-than-usual equipment.", 0, 40, 0, 0, 2, weapon_type.melee, false, 720, s_hammer, "boreal_sledge", 3)
add_weapon(item.wight_blade, "Wight Blade", "An old Regent Blade, chipped and rusted from time and use. The blade has been reseated in a new, bony hilt that has been imbued with arcane energy.", 6, 0, 0, 5, 1, weapon_type.melee, true, 248, s_shortsword, "wight_blade", 3)
add_weapon(item.holy_lance, "Holy Lance", "A mass-produced verison of the fabled Lance of Longinus. Despite its mass-produced nature, it is till failry potent.#As with all divine weapons, this weapon has relatively-speaking low damage, but will slowly heal its wielder.", 0, 0, 60, 0, 2, weapon_type.melee, false, 1300, s_spear, "holy_lance", 6, enemy_race.demon)
add_weapon(item.heavenly_blade, "Heavenly Blade", "The standard-issue weapon for divine soldiers. Infused with holy water and forged from sidirite, this is a fine weapon for killing foes both mundane and supernatural.#As with all divine weapons, this weapon has relatively-speaking low damage, but will slowly heal its wielder.", 60, 0, 0, 0, 1, weapon_type.melee, false, 1300, s_longsword, "heavenly_blade", 6, enemy_race.demon)
add_weapon(item.angel_soul, "Angel Soul", "Once, there was an angel who was immensely gifted in the arcane arts. Cast off from their kind for this association, the angel wallowed in the mortal world. Fed up with a boring, quiet life, the angel condensed their soul into this very catalyst.#As with all divine weapons, this weapon has relatively-speaking low damage, but will slowly heal its wielder.", 0, 0, 0, 60, 2, weapon_type.staff, false, 1300, s_soul, "angel_soul", 6, enemy_race.divine)
add_weapon(item.divine_hammer, "Divine Hammer", "An angel once offhandedly referred to their demon-hunting duties as a protracted game of whack-a-mole. Their friend seemed to have taken that analogy a little too far.#As with all divine weapons, this weapon has relatively-speaking low damage, but will slowly heal its wielder.", 0, 60, 0, 0, 2, weapon_type.melee, false, 1300, s_hammer, "divine_hammer", 6, enemy_race.demon) 
add_weapon(item.dawnfury, "Dawnfury", "A blade forged from an angel's unbrideled fury towards demons. So great was their fury, that the weapon is imbued with high arcane damage as well. As with all divine weapons, this weapon has relatively-speaking low damage, but will slowly heal its wielder.", 40, 0, 0, 35, 2, weapon_type.melee, true, 1300, s_longsword, "dawnfury", 6, enemy_race.demon)
add_weapon(item.angellic_axe, "Angellic Axe", "A hand-axe blessed with divine might. It emits a heavenly glow, showing its potential both as a catalyst and its enchanted nature.#As with all divine weapons, this weapon has relatively-speaking low damage, but will slowly heal its wielder.", 30, 0, 0, 25, 1, weapon_type.melee, true, 1300, s_1h_axe, "angellic_axe", 6)
add_weapon(item.seraphaxe, "Seraphaxe", "A greataxe forged from a dying angel's wings. Their dying breath enchanted the weapon, allowing its use as a catalyst, while also adding magic damage to its every swing.#As with all divine weapons, this weapon has relatively-speaking low damage, but will slowly heal its wielder.", 45, 0, 0, 15, 2, weapon_type.melee, true, 1300, s_2h_axe, "seraphaxe", 6)
add_weapon(item.runic_blade, "Runic Blade", "A shortsword that has had powerful arcane runes etched into it.##This weapon is enchanted, meaning that it will not only act as a catalyst, but it will deal magic damage along with its other damage output.", 40, 0, 0, 15, 1, weapon_type.melee, true, 850, s_shortsword, "runic_blade", 5)
add_weapon(item.runic_axe, "Runic Axe", "A handaxe that has had powerful arcane runes etched into it.##This weapon is enchanted, meaning that it will not only act as a catalyst, but it will deal magic damage along with its other damage output.", 22, 18, 0, 15, 1, weapon_type.melee, true, 850, s_1h_axe, "runic_axe", 5)
add_weapon(item.runic_spear, "Runic Spear", "A spear that has had powerful arcane runes etched into it.##This weapon is enchanted, meaning that it will not only act as a catalyst, but it will deal magic damage along with its other damage output.", 0, 0, 40, 15, 2, weapon_type.melee, true, 850, s_spear, "runic_spear", 5)
add_weapon(item.runic_mace, "Runic Mace", "A mace that has had powerful arcane runes etched into it.##This weapon is enchanted, meaning that it will not only act as a catalyst, but it will deal magic damage along with its other damage output.", 0, 40, 0, 15, 1, weapon_type.melee, true, 850, s_club, "runic_mace", 5)
add_weapon(item.demon_greatsword, "Demon Greatsword", "A hellish, corrupted blade. Said to be forged from the gnarled arm-bone of a corpulent Demon Sage.##Like all demon weapons, this has high damage, but each attack will cost 3% of your maximum health.", 100, 30, 0, 0, 2, weapon_type.melee, false, 6660, s_longsword, "demon_greatsword", 7, enemy_race.divine)
add_weapon(item.infernal_column, "Infernal Column", "That is just a pillar someone ripped out of a fallen temple in Hell, yes indeed.##Like all demon weapons, this has high damage, but each attack will cost 3% of your maximum health.", 0, 120, 0, 0, 2, weapon_type.melee, false, 1666, s_hammer, "infernal_column", 7, enemy_race.divine)
add_weapon(item.traitor_falchion, "Traitorous Falchion", "A falchion designed by a repentant demon, made to be more effective against its brethren. Demons value few things, but loyalty is surprisingly important to them, making this blade's existence doubly painful to them.##Like all demon weapons, this has high damage, but each attack will cost 3% of your maximum health.", 75, 0, 0, 15, 1, weapon_type.melee, true, 1666, s_shortsword, "traitor_falchion", 7, enemy_race.demon)
add_weapon(item.slade_club, "Slade Club", "A club hewn from slade. An anomalous rock that forms the foundations of Hell, slade is incredibly dense and heavy, indicating that this was created by a demon who was both skilled and humongous.##Like all demon weapons, this has high damage, but each attack will cost 3% of your maximum health.", 0, 90, 0, 0, 1, weapon_type.melee, false, 1666, s_club, "slade_club", 7, enemy_race.divine)
add_weapon(item.hateful_heart, "Hateful Heart", "The heart of a particularly ornery Demon Sage, the arcane forces that they dabbled in have made this heart a surprisingly effective catalyst.##Like all demon weapons, this has high damage, but each attack will cost 3% of your maximum health.", 0, 0, 0, 100, 2, weapon_type.staff, false, 1666, s_demon_heart, "demon_heart", 7)
add_weapon(item.corrupted_spear, "Corrupted Spear", "Some depraved demon decided it would be hillarous to take a dead angel's spear and twist it into a nightmarish shadow of its former self. Humor may be subjective, but this spear's power is not.##Like all demon weapons, this has high damage, but each attack will cost 3% of your maximum health.", 0, 0, 120, 0, 2, weapon_type.melee, false, 1666, s_spear, "corrupted_spear", 7, enemy_race.divine)
add_weapon(item.sadist_scimitar, "Sadist Scimitar", "A wicked scimitar, originally silver in color. Years of using this blade for all kinds of heinous torture have stained it an unnerving shade of rusty red.", 52, 0, 0, 0, 1, weapon_type.melee, false, 750, s_shortsword, "sadist_scimitar", 5)
add_weapon(item.lifedrinker, "Lifedrinker", "An obsidian claymore lined with strange, red grooves. Through various horrid rituals, this sword has gained a morbid thirst.##This weapon will increase your maximum HP by 1 when you land a kill with it.", 25, 0, 0, 15, 2, weapon_type.melee, true, 800, s_longsword, "lifedrinker", 5)
add_weapon(item.shattermallet, "Shattermallet", "Assembled from unstable, arcane ore, this hammer is so powerful, it can barely contain itself.", 0, 60, 0, 0, 2, weapon_type.melee, false, 800, s_2h_axe, "ethereal_greataxe", 5)
add_weapon(item.ethereal_greataxe, "Ethereal Greatxe", "A greataxe whose blade seems to be summoned from the aether. It crackles with energy and emits a small hum. Just what is this odd weapon?", 37, 5, 6, 8, 2, weapon_type.melee, true, 800, s_2h_axe, "ethereal_greataxe", 5)
add_weapon(item.rogues_pick, "Rogue's Pick", "A simple, but effective vehicle of puncture-related deaths. What the Rogues sometimes lack in flashiness, they make up for in deadliness.", 0, 0, 38, 0, 1, weapon_type.melee, 1, 750, s_shortsword, "rogues_pick", 5)

add_weapon(item.demonsbane_sword, "Demonsbane", "A powerful weapon, reforged long after the First Slayer's passing. This sword was forged from the tooth of an elder demon, and was so thoroughly sharpened that when the Slayer used it, they could gut any demon with one swing.", 115, 0, 0, 0, 1, weapon_type.melee, false, 1, s_longsword, "demonsbane_sword", 8, enemy_race.demon)
add_weapon(item.demonsbane_spear, "Demonsbane", "A powerful weapon, reforged long after the First Slayer's passing. This spear was made from the sharpened bones of a Demonlord, and it was said it could penetrate any armor in existence.", 0, 0, 115, 0, 1, weapon_type.melee, false, 1, s_spear, "demonsbane_spear", 8, enemy_race.demon)
add_weapon(item.demonsbane_mace, "Demonsbane", "A powerful weapon, reforged long after the First Slayer's passing. This mace was taken from Yar'Vith, one of the Greater Evils. The First Slayer quickly found that the mace crushed demon heads as easily as it crushed human heads.", 0, 115, 0, 0, 1, weapon_type.melee, false, 1, s_hammer, "demonsbane_hammer", 8, enemy_race.demon)
add_weapon(item.demonsbane_knives, "Demonsbane", "A powerful weapon, reforged long after the First Slayer's passing. These arcane knives coalesced upon the Slayer's destruction of an entire kingom within Hell, and it is said that they killed hundreds of demons afterwards without even having to lift a finger.", 30, 0, 0, 85, 1, weapon_type.melee, true, 1, s_shortsword, "demonsbane_knives", 8, enemy_race.demon)

add_weapon(item.starcutter, "Starcutter", "A blade that was once said to have sheared through various dimesions, finally coming to rest in this one. Made from unknown metals and seething with unknwon energy, it has retained its glory over the eons. Occasionally, making a kill with Starcutter will grant you extra experience.", 80, 0, 0, 30, 1, weapon_type.melee, true, 1, s_shortsword, 8, "starcutter")
add_weapon(item.longinus, "Longinus", "The Lance of Gods. Once coveted by the divine host, it was destroyed long ago when demonkind had nealry overrun the Divine Armory. It was one of the first weapons made with the power to kill a god.", 0, 0, 110, 30, 2, weapon_type.melee, true, 1, s_spear, "longinus", 8, enemy_race.divine)
add_weapon(item.fjolnir, "Fjolnir", "A hammer crafted by a smith who wanted to go down in history. When the gods learned that a human was trying to make a weapon that could harm them, they smited the smith, although the hammer was lost to history. A small shard of the smith's soul lives on in their weapon. Occasionally, on hit, Fjolnir will enrage you, doubling any damage taken and given for half an hour.", 0, 120, 0, 0, 1, weapon_type.melee, false, 1, s_hammer, "fjolnir", 8, enemy_race.divine)
add_weapon(item.quakehammer, "Quakehammer", "A gargantuan, mighty hammer. It's said that this hammer was used to raise mountains and flatten continents when the planet was young, but was thought lost for eons. Now, found once more, it is ready to turn any enemy you face into a red stain on the ground. Occasionally, an attack will cause a quake, dealing damage to all enemies on the floor.", 0, 150, 0, 0, 2, weapon_type.melee, false, 1, s_hammer, "quakehammer", 8)
add_weapon(item.dragonclaw, "Dragonclaw", "A handaxe forged from a dragon's claw, naturally. Imbued with cruel fire, this weapon was passed around for centuries, as it would go inert when wielded by one who was unworthy. Newly reforged, the axe shines birght in your hands. Occasionally, attacking will cause an explosion centered on you.", 30, 40, 0, 30, 1, weapon_type.melee, true, 1, s_1h_axe, "dragonclaw", 8)
add_weapon(item.final_word, "Final Word", "A massive executioner's axe. The blade has been stained permanently red, and this weapon is infamous for taking the lives of prisoners and executioners alike. It was destroyed by humans after discovering that it had its own lust for blood, and now hungers for more human heads to roll. Occasionally, it will cause a deep wound, crippling an enemy permanently and lowering their attack.", 90, 35, 0, 0, 2, weapon_type.melee, false, 1, s_2h_axe, "final_word", 8, enemy_race.human)
add_weapon(item.hollow_wand,"Hollow Wand", "A wand that, true to its name, has no traditional core. Instead, it filled with healing essence. This wand may occasionally heal you when you cast a spell.", 0, 20, 0, 90, 1, weapon_type.staff, false, 1, s_wand, "hollow_wand", 8)
add_weapon(item.yggdrastave, "Yggdrastave", "A staff formed from a branch of another dimension's World Tree. This staff emanates otherwordly arcane energies, and yet, calms and rejuvenates its user. Casting spells with this staff will sometimes not cost any energy.", 0, 30, 0, 120, 2, weapon_type.staff, false, 1, s_staff, "yggdrastave", 8)
add_weapon(item.gotterdammerung, "Gotterdammerung", "A heavy blade that is said to be capable of bringing about the end times. Unlike most of the Divine Forge's creations, this one is entirely unique, given to you to acknowledge the hardships you have faced. Occasionally, a kill with this blade will increase a random stat.", 110, 0, 0, 60, 2, weapon_type.melee, true, 1, s_longsword, "god_sword", 8, enemy_race.divine)
add_weapon(item.grim_scythe, "Grim Scythe", "A ghastly scythe, used to liberate the souls of the dead. While Death is usually stingy about mortals using Its power, It knows that you have faced death many times, and is interested in seeing what a mortal will do with Its prized weapon. This scythe will also, very rarely, kill its target in one hit.", 44, 0, 0, 40, 2, weapon_type.melee, true, 1, s_scythe, "grim_scythe", 8)
add_weapon(item.rabid_tooth, "Rabid Tooth", "The hound was once a kind thing. Loyal, loving, and empathetic, it served its master well. Whatever twisted this poor pup into a rabid killing machine will pay dearly.", 13, 0, 10, 0, 1, weapon_type.melee, false, 500, s_fang, "rabid_fang", 5, enemy_race.human)

//Guns
add_gun(item.derringer, "Derringer", "A small, weak pistol. While handy as a backup weapon, easy to conceal, and fairly accurate, that's really where its only strengths lie. The ammunition used in derringers leave small, relatively clean holes in their victims, making them a favorite of the criminal underworld.", 0, 0, 20, 0, 1, 1, 85, 5, 35, s_smallgun, "derringer", 1)
add_gun(item.slugthrower, "Slug Thrower", "A shotgun that fires heavy slugs. It's not the most accurate, but it hits like a ton of bricks. Slugs are preferred over scattershot due to the fact that slugs can stumble an opponent, on the off-chance the slug doesn't blow a hole clean through them.", 0, 8, 16, 0, 2, 2, 60, 4, 60, s_biggun, "slug_thrower", 1)
add_gun(item.clockrifle, "Clock Rifle", "A rifle that uses a special technique to cycle ammo quickly. This rifle is standard-issue for gunners in the Frontier Army, although some lament how often it has to be oiled. Especially since the oil smells like sin.", 0, 0, 35, 0, 2, 2, 80, 5, 120, s_biggun, "clock_rifle", 2)
add_gun(item.wess_smithy_200, "Wess-Smithy 200", "A powerful revolver. Wess-Smithy was one of the first companies to produce firearms, and they are well-known for their powerful sidearms in particular. It's almost tradition that a newly-promoted sergeant in the Frontier Army receives the latest model of WS handgun,", 0, 9, 29, 0, 1, 2, 85, 3, 550, s_smallgun, "ws_200", 3)
add_gun(item.scoper, "Scoper", "A ramshackle, homemade sniper rifle. While the Frontier Army strives to standardize its equipment allocations, their recent recruitment drives, along with general economic problems, have resulted in a shortage of standard-issue weapons. This has paved the way for bootleggers to sell homemade firearms of dubious and varying quality.", 0, 0, 50, 0, 2, 2, 90, 3, 620, s_biggun, "scoper", 3)
add_gun(item.duckfoot, "Duckfoot", "Someone once thought that the answer to getting more shots out of a pistol was to tape extra barrels onto it. Whether or not that works is going to come down to your gunslinging skills.", 0, 0, 70, 0, 1, 4, 60, 5, 980, s_smallgun, "duckfoot", 4)
add_gun(item.boomstick, "Boomstick", "A double-barrel, break-action shotgun. You can sense that this weapon originated in a different world. It's worn, scratched, and aged, but it'll still show any primitive screwheads you run into a groovy time.", 0, 25, 65, 0, 1, 2, 70, 4, 1269, s_biggun, "boomstick", 5)
add_gun(item.legion, "Legion", "A triple-barrelled revolver. Unlike most of the other weapons brought back from the Divine Forge, this one is an entirely new creation. It certainly seems that the Forgemasters believe in overkill. Very occasionally, the damage done by Legion will be tripled.", 0, 0, 90, 20, 1, 3, 80, 5, 1, s_smallgun, "legion", 8)
add_gun(item.harkonean, "Harkonean", "A disturbingly massive rifle. While not the most accurate, woe be to anything caught in this beast's sights. It is said that this rifle was once used to repel a vampire invasion in the distant past, although there's been no such concrete evidence of this found. Occasionally, the shells fired will explode on impact, damaging nearby creatures.", 0, 90, 30, 20, 2, 6, 75, 5, 1, s_biggun, "harkonean", 8)

//Armor
add_armor(item.leather_vest, "Leather Vest", "A simple, worn vest. Almost the bare-minimum of protection, you can't help but wonder what happened to its previous owner.", 1, 1.1, 1.1, 1, 1, 38, s_armor, "leather_vest", 2)
add_armor(item.old_shirt, "Old Shirt", "It's solidified from lack of cleaning. It's smelly, crusty, itchy, and stained, but it's better than nothing.", 0, 1.05, 1.05, 1.05, 1, 18, s_armor, "old_shirt", 1)
add_armor(item.plate_shirt, "Plate Shirt", "A shirt that has been reinforced with some plate metal. It's a bit uncomfortable, but you're probably better off uncomfortable than dead.", 1, 1.15, 1.15, 1, 0.65, 148, s_heavy_armor, "plate_shirt", 2)
add_armor(item.chainmail, "Chainmail", "A piece of armor made from inter-linked bits of chain, hence the name. This armor makes a joke of cutting weapons, but figthers quickly established that even the finest chainmail can fall victim to vicious poking.", 2, 1.5, 0.5, 1.05, 0.8, 240, s_heavy_armor, "chainmail", 2)
add_armor(item.robe, "Thin Robe", "A basic traveling robe. Lightly enchanted, it can guard against lower-power magic attacks, and not much else. Robes are often used when facing magic opponents, as heavier armor can slow the combatant down, or conduct magic attacks, if said armor is metallic.", 1, 0.75, 0.75, 0.75, 1.3, 19, s_robe, "thin_robes", 2)
add_armor(item.duster, "Duster", "A reinforced brown long coat, standard-issue for the Frontier Army when clearing out the fiend-infested Hinterlands. It offers fair defense, on top of being laced with potent anti-magic protections.", 2, 1, 1, 0.8, 1.4, 190, s_robe, "duster", 2)
add_armor(item.bloody_robe, "Bloody Robe", "A robe stained with the blood of hundreds. While its origins are unkown, its tattered appearane would suggest a long, storied history. A malevolent spirit seems to haunt this tatty robe. As such, enemies will occasionally take some of the damage they deal to you.", 1, 0.7, 0.8, 0.9, 1.4, 450, s_robe, "bloody_robe", 3)
add_armor(item.regent_plate, "Regent Plate", "A chestplate woven with Boreal steel. The Regent Knights strive to balance their equipment for speed, power, and protection, even if it tends to cost more to do so.", 2, 1.5, 1.5, 0.8, 0.8, 620, s_armor, "regent_plate", 3)
add_armor(item.scale_mail, "Scale Mail", "A suit of armor made from the hardened skin of a reptillian demon. While somewhat unorthodox, its effectiveness has been proved time and again throughout history.", 4, 1.2, 0.8, 1.1, 1, 400, s_armor, "scale_mail", 5)
add_armor(item.alliance_robe, "Alliance Robe", "A moderately-enchanted robe used by mid-ranking members of the Arcane Alliance. While still offering some rather poor physical defense, anyone who wears this will be able to shrug off some pretty nasty magic.", 2, 0.90, 0.70, 0.90, 1.6, 580, s_robe, "ally_robe", 3)
add_armor(item.reinforced_robe, "Reinforced Robe", "A robe lined with armored padding. While most arcanists prefer to stay out of direct combat, those who enlist in the Frontier Army must except that they must accept that sometimes, long-range spell-flinging won't do the job alone.", 2, 1.1, 1.1, 1.05, 1.4, 630, s_robe, "reinforced_robe", 3)
add_armor(item.commanders_jacket, "Commander's Jacket", "A heavily-modified duster, made for high-ranking officials within the Frontier Army. Promotion and having a high rank in the Frontier Army will rarely save you from fighting the enemy, but at least you'll be well-protected there.", 3, 1.2, 1.2, 1, 1.3, 720, s_robe, "comm_jacket", 4) 
add_armor(item.tower_plate, "Tower Plate", "The knight fought for justice. The Tower would fall, no matter the cost. Take up their armor, and finish their fight.", 4, 1.33, 1.33, 1.33, 1.33, 400, s_heavy_armor, "tower_plate", 6)
add_armor(item.baria_armor, "Baria Armor", "With a mix of arcane forces, this armor wills itself into existence. Baria cystals are a highly sought-after commodity, and when enchanted and strengthened with choice spells, create a magic shell around its holder.", 0, 1.2, 1.2, 1.2, 1.8, 3500, s_baria_crystal, "baria_armor", 5) 
add_armor(item.steelthread_cloak, "Steelthread Cloak", "A special cloak woven from steelthread, and imbued with powerful protection magic. This is the best protection most Arcanists will get, and even some more melee-inclined heroes throughout the ages have been spotted wearing this.", 4, 1.2, 1.05, 1.3, 1.4, 6500, s_robe, "steelthread_cloak", 5)
add_armor(item.mirror_plate, "Mirror Plate", "This magic armor will reflect any magic attacks thrown at you. It will also reflect the look of fear as a fiend sees its own magic missile being returned to sender with extreme predjudice.", 2, 1.1, 1.5, 1, 1, 800, s_heavy_armor, "mirror_plate", 6)
add_armor(item.obsidian_chainmail, "Obsidian Chainmail", "Chainmail that has, oddly, been forged out of a special form of obsidian. Normally, obsidian is fragile, being a volcanic glass and all. However, when treated properly, both physically and magically, it can become a lightweight, yet trusty armor material.", 5, 1.3, 1.1, 0.6, 1.25, 850, s_heavy_armor, "obsidian_chainmail", 6)
add_armor(item.plot_armor, "Plot Armor", "You can't die yet. I still need you for...reasons.#If you somehow got this and arne't me, disregard the above and delete your character immediately.#-Nick", 99, 5, 5, 5, 5, 1, s_baria_crystal, "plot_armor", 99)

//Shields
add_shield(item.wood_shield, "Wooden Slab", "A crude blocking implement. Necessity is the mother of invention, however, and if it keeps you alive, there's no point in complaining.", 8, 0.5, 50, s_shield, "wooden_slab", 1)
add_shield(item.recruit_shield, "Recruit's Shield", "Issued to prospective adventurers. The seal on the shield is that of the Delvers, a group responsible for most of the ruins exploration and exploitation of the world.", 12, 0.7, 85, s_shield, "recruits_shield", 2) 
add_shield(item.pot_lid, "Pot Lid", "It's...a pot lid. It smells like rotten stew, and the caked-on slime and grime are probably the only things that make this rusty chunk of metal usable as a shield.", 5, 0.25, 1, s_shield, "pot_lid", 1)
add_shield(item.scrap_targe, "Scrap Targe", "Necessity is the mother of invention. This is the flimsy excuse given for the slap-dash construction of this rusty amalgamation of scrap metal.", 7, 0.35, 40, s_shield, "scrap_targe", 1)
add_shield(item.buckler, "Buckler", "A sturdy, round, wooden shield, banded with iron. While not the flashiest of blocking implements, it has saved many a fighter from certain death.", 14, 0.60, 190, s_shield, "buckler", 2)
add_shield(item.regent_shield, "Regent Shield", "A thin, but deceptively-protective shield inlaid with steel. Made for mobility, these shields have saved many a knight, and their durability is legendary, even among the general public.", 18, 0.75, 350, s_shield, "regent_shield", 3)
add_shield(item.ingot_shield, "Ingot Shield", "A shield that is mostly just an abnormaly large ingot of steel. Its crafter was either lazy, unskilled, or into some postmodernistic thoughts on shields.", 12, 0.9, 375, s_shield, "ingot_shield", 3)
add_shield(item.sanguine_shield, "Sanguine Shield", "Forged with vampiric blood, this shield is nonetheless rather flimsy. However, said vampiric blood has imbued this shield with the ability to heal its user when used to successfully block an attack.", 10, 1, 400, s_big_shield, "sanguine_shield", 4)
add_shield(item.druidic_shield, "Druidic Shield", "A shield woven from living roots. While its blocking capabilities leave much to be desired, its life-giving aura will slow the rate at which its wielder's energy decreases.", 19, 0.3, 600, s_big_shield, "druidic_shield", 5)
add_shield(item.kite_shield, "Kite Shield", "Unfortunately not a shield that can be flown like a kite. Made from ironwood and banded by Borean Steel, few things make it past this shield's defenses.", 22, 0.9 , 550, s_shield, "kite_shield", 4)
add_shield(item.rock_shield, "Rock Shield", "A shield hewn from rock. Legends tell of a knight who wore nothing but rock, ate nothing but rock, and was nothing but rock. In fact, this hero may have been a golem. Regardless, their shield is now yours. It's been enchanted so that it may be held in one hand.", 20, 1, 3000, s_big_shield, "rock_shield", 9)
add_shield(item.avarice_shield, "Targe of Avarice", "A flimsy shield made of gold. Although not very effective for blocking, this shield will increase the value of all Zun dropped by 50 percent.", 5, 0.1, 650, s_big_shield, "avarice_shield", 5)
add_shield(item.god_shield, "God Shield", "Will block everything short of a short-range nuclear detonation. Or it might even block that.##Also, this is a dev item. Why do you have this?#-Nick", 999, 1, 1, s_big_shield, "god_shield", 99)

//Set items

//Champion's Courage
add_weapon(item.simple_sword, "Simple Sword", "A sword. It seems simple, yet powerful...##Set: Champion's Courage#(Simple Sword, Azure Mail, Goddess Shield)#Complete Set Bonus: All damage taken reduced by half.", 38, 0, 0, 0, 1, weapon_type.melee, false, 3333, s_shortsword, "simple_sword", 10)
add_armor(item.azure_mail, "Azure Mail", "A set of blue armor. Wearing it gives you a strange sense of courage...##Set: Champion's Courage#(Simple Sword, Azure Mail, Goddess Shield)#Complete Set Bonus: All damage taken reduced by half.", 4, 1.5, 1.5, 1.5, 1.5, 3333, s_azure_mail, "azure_mail", 10)
add_shield(item.goddess_shield, "Goddess Shield", "A shield adorned by the mark of an unkown goddess. Truly a shield for the wise...##Set: Champion's Courage#(Simple Sword, Azure Mail, Goddess Shield)#Complete Set Bonus: All damage taken reduced by half.", 25, 0.8, 3333, s_shield, "goddess_shield", 10)

//Gutsy Garb
add_weapon(item.drake_smasher, "Drake Smasher", "A hunk of Boreal iron masquearading as a sword.##Set: Gutsy Garb#(Drake Smasher, Armor of Rage)#Complete Set Bonus: Occasionally go into a rage and do 4x damage.", 1, 37, 0, 0, 2, weapon_type.melee, false, 3333, s_drake_smasher, "drake_smasher", 10, enemy_race.gothic)
add_armor(item.armor_of_rage, "Armor of Rage", "Armor made from shreds of iron, cloth, leather, and anger.##Set: Gutsy Garb#(Drake Smasher, Armor of Rage)#Complete Set Bonus: Occasionally go into a rage and do 4x damage.", 2, 1.15, 0.6, 1.9, 1.1, 3333, s_heavy_armor, "armor_of_rage", 10)

//Sign of Shadows
add_weapon(item.stealthy_spear, "Stealthy Spear", "Why get close when you can backstab someone with a ten-and-a-half-foot pole?##Set: Sign of Shadows#(Stealthy Spear, Cloak of Shadows)#Complete Set Bonus: Occasionally go into stealth mode when hit.", 0, 0, 30, 5, 2,weapon_type.melee, true, 3333, s_spear, "stealthy_spear", 10)
add_armor(item.cloak_of_shadows, "Cloak of Shadows", "A cloak that seems to be made from pure DARKNESS.##Set: Sign of Shadows#(Stealthy Spear, Cloak of Shadows)#Complete Set Bonus: Occasionally go into stealth mode when hit.", 1, 0.6, 0.6, 1.2, 3, 3333, s_cloak_shadows, "cloak_of_shadows", 10)

//Panoply of Potential
add_weapon(item.sword_of_sacrifice, "Sword of Sacrifice", "The Vagabond Monarch's last rite.##Set: Panoply of Potential#(Sword of Sacrifice, Worn Raiment, Royal Targe)#Complete Set Bonus: Kills increase a random stat.", 30, 0, 0, 0, 1, weapon_type.melee, false, 3333, s_shortsword, "sword_of_sacrifice", 10)
add_armor(item.worn_raiment, "Worn Raiment", "The Fallen Monarch's only memory of prosperity.##Set: Panoply of Potential#(Sword of Sacrifice, Worn Raiment, Royal Targe)#Complete Set Bonus: Kills increase a random stat.", 2, 1.3, 1.5, 1.2, 0.5, 3333, s_robe, "worn_raiment", 10)
add_shield(item.royal_targe, "Royal Targe", "The Guardian Monarch's left-hand companion.##Set: Panoply of Potential#(Sword of Sacrifice, Worn Raiment, Royal Targe)#Complete Set Bonus: Kills increase a random stat.", 30, 0.7, 3333, s_shield, "royal_targe", 10)

//Astral Apparel
add_weapon(item.cosmic_catalyst, "Cosmic Catalyst", "A powerful shard of a long-dead star.##Set: Astral Apparel#(Cosmic Catalyst, Starry Robes)#Complete Set Bonus: Spells will occasionally not cost energy.", 0, 0, 7, 45, 2, weapon_type.staff, false, 3333, s_soul, "cosmic_catalyst", 10)
add_armor(item.starry_robes, "Starry Robes", "A robe that reflects the night sky.##Set: Astral Apparel#(Cosmic Catalyst, Starry Robes)#Complete Set Bonus: Spells will occasionally not cost energy.", 2, 0.7, 0.7, 0.5, 3, 3333, s_starry_robe, "starry_robe", 10)

//Demonic Duds
add_armor(item.infernal_armor, "Infernal Armor", "Armor forged from the corpse of a Ruler of Hell.##Set: Demonic Duds#(Infernal Armor, Icon of Hell)#Complete Set Bonus: Deal 4x damage to all demons.", 4, 1, 1.6, 1, 1.3, 3333, s_heavy_armor, "infernal_armor", 10)
add_shield(item.icon_of_hell, "Icon of Hell", "Use the demonic blight's icon against them.##Set: Demonic Duds#(Infernal Armor, Icon of Hell)#Complete Set Bonus: Deal 4x damage to all demons.", 66, 0.6, 3333, s_icon_of_hell, "icon_of_hell", 10) 

//Veteran's Vestments
add_weapon(item.privates_pistol, "Private's Pistol", "Engraved with icons of hope and determination.##Set: Veteran's Vestments#(Private's Pistol, Ancient Duster, Guard Gauntlet)#Complete Set Bonus: When shooting, occasionally fire in a 3x3 radius of you.", 0, 14, 20, 0, 1, weapon_type.gun, false, 3333, s_smallgun, "privates_pistol", 10)
add_armor(item.ancient_duster, "Ancient Duster", "Worn by the very first Frontier Soldier.##Set: Veteran's Vestments#(Private's Pistol, Ancient Duster, Guard Gauntlet)#Complete Set Bonus: When shooting, occasionally fire in a 3x3 radius of you.", 3, 1.3, 1.3, 1.3, 1.3, 3333, s_robe, "ancient_armor", 10)
add_shield(item.guard_gauntlet, "Guard Gauntlet", "An experimental, light-weight shield.##Set: Veteran's Vestments#(Private's Pistol, Ancient Duster, Guard Gauntlet)#Complete Set Bonus: When shooting, occasionally fire in a 3x3 radius of you.", 30, 0.7, 3333, s_gauntlet, "guard_gauntlet", 10)



//Food
add_food(item.meatshroom, "Meatshroom", "A meaty fungus. It has a fleshy texture, and tastes like a fine steak when cooked properly. Many people use this as a substitute to meat, although some find its texture unpalatable.",
4, 0, 0, 0, 0, 8, 25, s_mushroom, "meatshroom")
add_food(item.rye, "Rye", "A heavy, dark bread. Perfect for dipping in some beef stew. While associated with peasents, some nobility use this bread for elaborate sandwiches.",
6, 0, 0, 0, 0, 5, 20, s_food, "rye")
add_food(item.beef_stew, "Beef Stew", "A hearty stew, made from beef and mixed vegetables. Popular in cold climates for its filling nature and warmth. Unfortunately, it has no pearl onions in it.",
10, 0, 0, 0, 0, 30, 105, s_stew, "beef_stew")
add_food(item.ration, "Ration", "A carefully-packed ration. Made up of tinned meat, hardtack, dessicated vegetables, and a small package of candy. Not very palatable, but there's plenty of it.",
20, 0, 0, 0, 0, 30, 200, s_can, "ration")
add_food(item.medkit, "Medkit", "A first-aid kit containing some essential supplies. It also comes with an emergency snack, since you really shouldn't eat bandages.",
5, 0, 0, 0, 0, 100, 200, s_can, "medkit") 
add_food(item.potroast, "Pot Roast", "A slow-cooked chunk of beef, seasoned with onion soup mix and accompanied by cut potatoes, carrots, and celery. It's always a wise idea to save the gravy, as pot roasts tend to dry out fairly easily.",
13, 0, 0, 0, 0, 25, 150, s_meal, "pot_roast")
add_food(item.icebergsalad, "Iceberg Salad", "A refreshing assortment of veggies mixed into some torn-up iceberg lettuce. Unfortunately, there doesn't seem to be any dressing on it.  It's healthier, sure, but at what cost?",
8, 0, 0, 0, 0, 45, 100, s_meal, "iceberg_salad")
add_food(item.knoefla, "Knoefla Soup", "A warm, comforting soup, made from potatoes and dumplings. A common dish in the Boreal Plains, but relatively unknown elsewhere.",
15, 0 ,0 ,0, 0, 20, 175, s_stew, "knoefla_soup")
add_food(item.trailmix, "Trail Mix", "A loose mixture of nuts, fruit, and chocolate that's meant to tide hikers over without making them too full to hike. It seems the maker was prudent enough to leave the enemy of humanity, raisins, out of it.",
6, 0 ,0, 0, 0, 18, 75, s_meal, "trail_mix") 
add_food(item.pemmican, "Pemmican", "A ball of protein and berries. Made from meat that is dried and crushed into a fine dust, before being mixed with fat and other additives. It's not particularly tasty on its own, but it can keep for years on end.",
7, 0, 0, 0, 0, 14, 100, s_food, "pemmican")
add_food(item.jerky, "Jerky", "Jerky made from some unidentified meat. While you can't tell what meat it was made from, it at least seems to be an authentic strip of meat, not some formed and over-salted stick of (more) unhealthiness.",
7, 0, 0, 0, 0, 20, 80, s_food, "jerky")
add_food(item.mana_treat, "Mana Bun", "A large bun covered in sweet glaze. These treats are a specialty of the Arcane Alliance, and are fortified to quickly restore the consumer's lost energy.", 
40, 0, 0, 0,  0, 0, 50, s_food, "mana_treat")
add_food(item.jelly, "Jelly", "Some jelly cultivated from a slime. It has a smooth, pleasent texture, and tastes like delicious candied apples.##Nah, just kidding. It's gritty and tastes like raw sewage. But, it IS nutritious, so bottoms up...",
10, 0, 0, 0, 0, 10, 100, s_jelly, "jelly")
add_food(item.food_scrap, "Scrap of Food", "An unidentifiable scrap of food. It looks like your messy eating habits have paid off.", 10, 0, 0, 0, 0, 0, 0, s_food, "food_scrap")


//Potions
add_food(item.musclemix, "Muscle Mix", "A mix of proteins, meat, raw eggs, and sharp rocks that will give you an extra point in Strength.", 
5, 1, 0, 0, 0, 10, 300, s_gray_potion, "muscle_mix")
add_food(item.sightsoda, "Sight Soda", "A smooth, creamy soda that heightens your senses, granting an extra point in Perception.",
5, 0, 0, 0, 1, 10, 300, s_orange_potion, "sight_soda")
add_food(item.cosmiccider, "Cosmic Cider", "A spiced cider, imbued with arcane and otherwordly powers, which will open your mind and give you an extra point in Wisdom.",
5, 0, 1, 0, 0, 10, 300, s_purple_potion, "cosmic_cider")
add_food(item.dexdrink, "Dex Drink", "A tangy, refreshing drink that perks you up and speeds up your reaction time, granting you an extra point in Dexterity.",
5, 0, 0, 1, 0, 10, 300, s_red_potion, "dex_drink")
add_food(item.energy_potion, "Energy Enhancer", "A special brew that will slow your metabolism, increasing your maximum energy by two points. Don't worry, the effects will wear off after you've conquered the Tower. Probably.",
5, 0, 0, 0, 0, 0, 400, s_brown_potion, "energy_potion")
add_food(item.distilled_essence, "Distilled Essence", "Demonic essence that has been decanted and preserved through arcane means. This dastardly brew holds 25% of your essence capacity. It smells like rotten sulfur and tastes like the souls of the damned. Bottoms up...",
0, 0, 0, 0, 0, 0, 100, s_distilled_essence, "distilled_essence")
add_food(item.small_heal_potion, "Mend Potion", "A specially-mixed, fast-acting tonic that will heal all your aches and pains. Heals 33% of your maximum hit points. The only downside is that it tastes like rotten cherries...",
0, 0, 0, 0, 0, 0, 200, s_small_heal_potion, "small_heal")
add_food(item.big_heal_potion, "Heal Potion", "A large dose of strong medicine. With the powers of science and hundreds of clinical trials, this will heal you for 66% of you maximum hit points instantly. Some have described its taste to be like bubblegum, while others swear tht it tastes like fresh tar.",
0, 0, 0, 0, 0, 0, 700, s_big_heal_potion, "big_heal")
add_food(item.grand_potion, "Grand Potion", "The pinnacle of medical science. This fortifying brew will fully heal you instantly, and will also give you some energy to boot. When asked how they made this amazing tonic, the creator revealed that it was simply a Mend and Heal potion put together, before the creator killed their interviewer.",
20, 0, 0, 0 , 0, 0, 2500, s_grand_potion, "grand_potion")
add_food(item.ambrosia_syrup, "Ambrosia Syrup", "A divine drink whose taste transcends conventional descriptions. This sacred syrup will restore you to full hit points and energy instantly, and will also grant you an instant level-up and a period of invincibility. Sleep well, knowing that you have eaten the food of the gods.",
0, 0, 0, 0, 0, 0, 7000, s_ambrosia_syrup, "ambrosia_syrup")
add_food(item.gold_dust, "Gold Dust", "A bottle of enchanted, golden dust. It is said to be shaved from the golden statue of a crying king. Applying this dust will allow every hit you land to make you money for a short time.", 0, 0, 0, 0, 0, 0, 500, s_gold_dust,"gold_dust")
add_food(item.ironbark_brew, "Ironbark Brew", "An...interesting...brew made from shaved Iron Oak bark. Somehow, when ground into dust and added to water, the resulting solution confers temporary, extra natural defense to anyone who drinks it.", 8, 0, 0,  0, 0, 10, 450, s_ironbark_brew, "ironbark_brew")
add_food(item.liquid_knowledge, "Liquid Knowledge", "A concoction totally not made from blended brains, this dubious drink will instantly give you 25% of the XP needed for your next level", 5, 0, 0, 0, 0, 15, 700, s_liquid_knowledge, "liquid_knowledge")
add_food(item.enchanted_salve, "Enchanted Salve", "A salve that has been foritifed with various arcane energies. Applying this to your weapon will temporarily enchant it, dealing a portion of its main damage as addtional magic damage.", 0, 0 ,0, 0, 0, 0, 350, s_enchanted_salve, "enchanted_salve")
add_food(item.water, "Jug o' Water", "It's just a jug of water. #...or is it?", 2, 0, 0, 0, 0, 2, 20, s_water_jug, "water")
add_food(item.star_essence, "Star Essence", "The distilled essence of a shooting star, said to grant invincibility to any who dare consume it. Some have even claimed to hear music when under the effects of this mysterious substance.", 10, 0, 0, 0, 0, 10, 650, s_star_essence, "star_essence")
add_food(item.perky_pop,  "Perky Pop", "This odd, fizzy drink will imbue you with a random perk. It will only give you a perk you don't own, and if there are no available perks left, it will instead raise you Dex, Per, Wis, and Str by 2.", 0, 0, 0, 0, 0, 0, 4000, s_pop, "perky_pop")
add_food(item.vampire_blood, "Vampire Blood", "A vial of blood, obtained from a powerful vampire. You swear you can hear the blood calling out to you, promising immortality and unholy power...", 0, 0, 0, 0, 0, 0, 4444, s_vampire_blood, "vampire_blood")
add_food(item.skull_talisman, "Skull Talisman", "This talisman depicts an alien-looking skull, flanked by ancient pictographs. The talisman is inexplicably made of sugar, which means it's edible, but there seems to be something...strange...about this edible effigy...", 10, 0, 0, 0, 0, 30, 4004, s_skull_talisman, "skull_talisman")

//Tomes
add_tome(item.tome_fireball, "Tome of Fireball", "A tome that can teach you how to cast the spell Fireball.", spell.fireball, 400, s_tome, "tome_fireball")
add_tome(item.tome_iceball, "Tome of Iceball", "A tome that can teach you how to cast the spell Iceball.", spell.ice_ball, 400, s_tome, "tome_iceball")
add_tome(item.tome_mend, "Tome of Mend", "A tome that can teach you how to cast the spell Mend.", spell.mend, 500, s_tome, "tome_mend")
add_tome(item.tome_quake, "Tome of Quake", "A tome that can teach you how to cast the spell Quake.", spell.quake, 600, s_tome, "tome_quake")
add_tome(item.tome_sense_monster, "Tome of Sense Mind", "A tome that can teach you how to cast the spell Sense Mind.", spell.sense_mind, 700, s_tome, "tome_sense_mind")
add_tome(item.tome_slow, "Tome of Slow", "A tome that can teach you how to cast the spell Slow.", spell.slow, 500, s_tome, "tome_slow")
add_tome(item.tome_stealth, "Tome of Stealth", "A tome that can teach you how to cast the spell Stealth.", spell.stealth, 600, s_tome, "tome_stealth")
add_tome(item.tome_explosion, "Tome of Explosion", "A tome that can teach you how to cast the spell Explosion.", spell.aoe_explosion, 800, s_tome, "tome_explosion")
add_tome(item.tome_landmine, "Tome of Landmine", "A tome that can teach you how to cast the spell Landmine.", spell.landmine, 750, s_tome, "tome_landmine")
add_tome(item.tome_magic_pillar, "Tome of Mag Pillar", "A tome that can teach you how to cast the spell Magic Pillar", spell.magic_pillar, 650, s_tome, "tome_magic_pillar")
